//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetaByte_KellysFeatures2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int cartId { get; set; }
        public string cartSessionId { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> GiftId { get; set; }
        public int count { get; set; }
    
        public virtual giftItem giftItem { get; set; }
    }
}
