//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetaByte_KellysFeatures2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationProfile
    {
        public int donationprofileId { get; set; }
        public string donationMessage { get; set; }
        public int donationId { get; set; }
    
        public virtual Donation Donation { get; set; }
    }
}
