//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetaByte_KellysFeatures2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Alerts = new HashSet<Alert>();
            this.JobPostings = new HashSet<JobPosting>();
            this.Navigations = new HashSet<Navigation>();
            this.Pages = new HashSet<Page>();
            this.SubNavigations = new HashSet<SubNavigation>();
        }
    
        public int employeeId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string position { get; set; }
        public int departmentId { get; set; }
        public Nullable<int> contactId { get; set; }
        public Nullable<int> addressId { get; set; }
        public Nullable<int> emerageContactID { get; set; }
        public System.DateTime birthDate { get; set; }
        public string sinNum { get; set; }
        public string schedule { get; set; }
        public string admin { get; set; }
        public Nullable<int> employeeStatusId { get; set; }
        public Nullable<int> insuranceId { get; set; }
    
        public virtual ICollection<Alert> Alerts { get; set; }
        public virtual ICollection<JobPosting> JobPostings { get; set; }
        public virtual ICollection<Navigation> Navigations { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<SubNavigation> SubNavigations { get; set; }
    }
}
