//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetaByte_KellysFeatures2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftOrder
    {
        public int id { get; set; }
        public int ProductId { get; set; }
        public int GiftBillId { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
    
        public virtual GiftBill GiftBill { get; set; }
        public virtual GiftItemCategory GiftItemCategory { get; set; }
    }
}
