//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetaByte_KellysFeatures2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetaByteContext : DbContext
    {
        public PetaByteContext()
            : base("name=PetaByteContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alert> Alerts { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<JobApplicant> JobApplicants { get; set; }
        public DbSet<JobPosting> JobPostings { get; set; }
        public DbSet<Navigation> Navigations { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<SubNavigation> SubNavigations { get; set; }
    }
}
