//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetaByte_KellysFeatures2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime joinDate { get; set; }
        public int roleId { get; set; }
        public int loginId { get; set; }
        public string phone { get; set; }
    
        public virtual Password Password { get; set; }
        public virtual Position Position { get; set; }
    }
}
